### PR TITLE
Added redirects

### LINKED ISSUE #34: Implement client-side redirects for all legacy docs URLs
[Implementing client-side redirects](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects) as specified in #35 through Docusaurus.

### PR DESCRIPTION
**Pull request by shanejonas**
This adds support for redirects from the old site pathsto mm-docs-v2 new paths we have.

fixes #34

### CODE REVIEW

**Comment by adonesky1** [comment]
How can I test this?

**Comment by vandan** [comment]
> How can I test this?

Although we can't test by hitting production URLs, can it be tested by hitting the relative paths for the redirects (everything after "https://docs.metamask.io/" from the redirect list [here](https://docs.google.com/spreadsheets/d/1-6NcE1L3y2OBMTgCLs3_Fdk9UCdwvsCyw2rx7nE0m-w/edit?usp=sharing))?

**Comment by shanejonas** [comment]
you need to run it with `yarn build && yarn serve` to see the redirects, they only work in the build with this plugin.

**Comment by adonesky1** [comment]
> you need to run it with yarn build && yarn serve to see the redirects, they only work in the build with this plugin.

Should we add this to the readme?

**Review by adonesky1 — APPROVED** [review]

**Pull request merged**
