### PR TITLE
Add note that the SDK uses the onboarding library

### LINKED ISSUE #87: Update docs and repos related to the onboarding library
The SDK incorporates functionality of the onboarding library.
Developers only really need the onboarding library if they're not integrating with the MetaMask SDK.

(see [slack thread](https://consensys.slack.com/archives/C02GENU377A/p1680117365262059) for more info)

### PR DESCRIPTION
**Pull request by alexandratran**
Add note at the top of the onboarding library page that the SDK incorporates the onboarding functionality. Fixes #87.

Preview: https://metamask.github.io/mm-docs-v2/87-onboarding/wallet/how-to/use-onboarding-library

### CODE REVIEW

**Comment by alexandratran** [comment]
@metamaskbot publish-preview

**Comment by vandan** [comment]
I didn't see a lot of guidance in the old docs either, but I'm wondering if there are some hints about how to utilize the features that are in the onboarding library from the SDK. 

cc @httpJunkie @andrepimenta who may know more

**Comment by vandan** [comment]
Looks like it auto-detects the `origin` so maybe there's not much more to explain here.

**Review by andreahaku — APPROVED** [review]
LGTM

**Review by bgravenorst — APPROVED** [review]
LGTM

**Pull request merged**
